server:
  port: 8070

eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSynEmpty: 5

spring: 
  cloud:
    loadbalancer:
      health-check: 
        initial-delay: 1s
        interval: 30s
      cache:
        caffeine: 
          spec: initialCapacity=10, maximumSize=50
        ttl: 30s
      stats: 
        micrometer: 
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false