example:
  property: I AM THE DEFAULT
  
  # 应用服务 WEB 访问端口
server:
  port: 8090
  
  # jpa
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  loadbalancer:
    health-check: 
      initial-delay: 1s
      interval: 30s
    cache:
      caffine:
        spec: initialCapacity=10, maximumSize=50
      ttl: 30s
    stats: 
      micrometer: 
        enabled: true
# eureka client
eureka:
  instance:
    preferIpAddress: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
    

logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        com.learn: DEBUG