server:
  port: 8072

# eureka client
eureka:
  instance:
    preferIpAddress: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka
    

# gateway

spring:
  cloud:
    gateway:
        discovery.locator:
            enabled: false
            lowerCaseServiceId: true

# management
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false