server:
  port: 8072

# eureka client
eureka:
  instance:
    preferIpAddress: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka
    

# gateway

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
        - id: facade
          uri: lb://facade
          predicates:
            - Path=/facade/**
          filters:
            - RewritePath=/facade/(?<path>.*), /$\{path}
    loadbalancer:
      health-check: 
        initial-delay: 1s
        interval: 30s
      cache:
        caffeine:
          spec: initialCapacity=10, maximumSize=50
        ttl: 30s
      stats: 
        micrometer: 
          enabled: true
          
# management
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false

logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        com.learn: DEBUG